export const ROLES = {
  CUSTOMER: 'СПМ',
  'GRID ACCESS PROVIDER': 'ОМ',
  'BALANCE SUPPLIER': 'СВБ',
  'METERING POINT ADMINISTRATOR': 'АТКО',
  'METER OPERATOR': 'ОЗКО',
  'METERED DATA COLLECTOR': 'ОЗД',
  'METERED DATA RESPONSIBLE': 'ОДКО',
  'METERED DATA AGGREGATOR': 'АДКО',
  'METERED RESPONSIBLE PARTY': 'ВТКО',
  'THIRD PARTY': 'Третя сторона',
  'SETTLEMENTS ADMINISTRATOR': 'АР',
  'SETTLEMENTS ADMINISTRATOR (READ ONLY)': 'АР (перегляд розширено)',
  'ADMINISTRATOR AR': 'Адміністратор АР',
  'COMMERCIAL METERING ADMINISTRATOR': 'АКО',
  'COMMERCIAL METERING ADMINISTRATOR DIRECTORY': 'АКО_Довідники',
  'COMMERCIAL METERING ADMINISTRATOR PROCESSES': 'АКО_Процеси',
  'COMMERCIAL METERING ADMINISTRATOR USERS': 'АКО_Користувачі',
  'COMMERCIAL METERING ADMINISTRATOR COMMERCIAL METERING SERVICE': 'АКО_ППКО',
  'COMMERCIAL METERING ADMINISTRATOR DISPUTES': 'АКО_Суперечки',
  'COMMERCIAL METERING ADMINISTRATOR AUDIT': 'АКО_Перевірки',
  'GUARANTEED BS': 'ГарПок',
  'CMA/SA_ZV': 'АКО/АР_ZV'
};

export const TYPE_OF_ACCOUNTING_POINT = {
  Consumption: 'TYPE_OF_ACCOUNTING_POINT.CONSUMPTION',
  Combined: 'TYPE_OF_ACCOUNTING_POINT.COMBINED',
  Production: 'TYPE_OF_ACCOUNTING_POINT.PRODUCTION',
  Exchange: 'TYPE_OF_ACCOUNTING_POINT.EXCHANGE'
};

export const CONNECTION_STATUSES = {
  Underconstruction: 'CONNECTION_STATUSES.UNDERCONSTRUCTION',
  'Disconnected by GAP': 'CONNECTION_STATUSES.DISCONNECTED_BY_GAP',
  Disconnected: 'CONNECTION_STATUSES.DISCONNECTED',
  'Disconnected by Cust': 'CONNECTION_STATUSES.DISCONNECTED_BY_CUST',
  'Disconnected by GAP&BS': 'CONNECTION_STATUSES.DISCONNECTED_BY_GAP&BS',
  Demolished: 'CONNECTION_STATUSES.DEMOLISHED',
  Connected: 'CONNECTION_STATUSES.CONNECTED'
};

export const FILE_PROCESSING_STATUSES = {
  NEW: 'FILE_PROCESSING_STATUSES.NEW',
  IN_PROCESS: 'FILE_PROCESSING_STATUSES.IN_PROCESS',
  DONE: 'FILE_PROCESSING_STATUSES.DONE',
  FAILED: 'FILE_PROCESSING_STATUSES.FAILED',
  BAD_FILE_STRUCTURE: 'FILE_PROCESSING_STATUSES.BAD_FILE_STRUCTURE'
};

export const COMPARE_CODES = {
  ua: 'uk',
  en: 'en'
};

export const MARKERS_DATA = {
  ФО: 'MARKERS_DATA.FO',
  ЮО: 'MARKERS_DATA.UO',
  'ФО-П': 'MARKERS_DATA.FOP',
  'ЮО-В': 'MARKERS_DATA.UOB'
};

export const DISCREPANCIES = {
  Лічильник: 'EQUIPMENT_TYPES.METER',
  'Трансформатор струму': 'EQUIPMENT_TYPES.CURRENT_TRANSFORMER',
  'Трансформатор напруги': 'EQUIPMENT_TYPES.VOLTAGE_TRANSFORMER',
  Інший: 'EQUIPMENT_TYPES.OTHER'
};
