
export const CONNECTION_STATUSES = {
  Underconstruction: 'CONNECTION_STATUSES.UNDERCONSTRUCTION',
  Disconnected: 'CONNECTION_STATUSES.DISCONNECTED',
  Demolished: 'CONNECTION_STATUSES.DEMOLISHED',
  Connected: 'CONNECTION_STATUSES.CONNECTED',
  'Disconnected by GAP': 'CONNECTION_STATUSES.DISCONNECTED_BY_GAP',
  'Disconnected by Cust': 'CONNECTION_STATUSES.DISCONNECTED_BY_CUST',
  'Disconnected by GAP&BS': 'CONNECTION_STATUSES.DISCONNECTED_BY_GAP&BS'
};
