// GLOBAL

export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';

// TOKEN

export const GET_TOKEN_STARTED = 'GET_TOKEN_STARTED';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const GET_TOKEN_BY_ESIGN_STARTED = 'GET_TOKEN_BY_ESIGN_STARTED';
export const GET_TOKEN_BY_ESIGN_SUCCESS = 'GET_TOKEN_BY_ESIGN_SUCCESS';
export const GET_TOKEN_BY_ESIGN_FAILURE = 'GET_TOKEN_BY_ESIGN_FAILURE';

export const NEED_OPT_TOKEN = 'NEED_OPT_TOKEN';

export const VERIFY_OTP_STARTED = 'VERIFY_OTP_STARTED';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const USER_LOG_OUT = 'USER_LOG_OUT';

export const VERIFY_TOKEN_STARTED = 'VERIFY_TOKEN_STARTED';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAILURE = 'VERIFY_TOKEN_FAILURE';
export const TOKEN_UNDEFINED = 'TOKEN_UNDEFINED';

export const SET_ACTIVE_ROLE_STARTED = 'SET_ACTIVE_ROLE_STARTED';
export const SET_ACTIVE_ROLE_FAILURE = 'SET_ACTIVE_ROLE_FAILURE';

// SNACKBAR

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

// TKO LIST

export const SET_TKO_PARAMS = 'SET_TKO_PARAMS';

export const GET_TKO_BY_ID_STARTED = 'GET_TKO_BY_ID_STARTED';
export const GET_TKO_BY_ID_SUCCESS = 'GET_TKO_BY_ID_SUCCESS';
export const GET_TKO_BY_ID_FAILURE = 'GET_TKO_BY_ID_FAILURE';

export const GET_TKO_ALL_ORGANIZATIONS_STARTED = 'GET_TKO_ALL_ORGANIZATIONS_STARTED';
export const GET_TKO_ALL_ORGANIZATIONS_SUCCESS = 'GET_TKO_ALL_ORGANIZATIONS_SUCCESS';
export const GET_TKO_ALL_ORGANIZATIONS_FAILURE = 'GET_TKO_ALL_ORGANIZATIONS_FAILURE';

// TKO DOWNLOAD

export const DOWNLOAD_TKO_STARTED = 'DOWNLOAD_TKO_STARTED';
export const DOWNLOAD_TKO_SUCCESS = 'DOWNLOAD_TKO_SUCCESS';
export const DOWNLOAD_TKO_FAILURE = 'DOWNLOAD_TKO_FAILURE';

// MASS_LOAD

export const UPLOAD_TKO_STARTED = 'UPLOAD_TKO_STARTED';
export const UPLOAD_TKO_SUCCESS = 'UPLOAD_TKO_SUCCESS';
export const UPLOAD_TKO_FAILURE = 'UPLOAD_TKO_FAILURE';

export const CLEAR_UPLOAD_DATA = 'CLEAR_UPLOAD_DATA';

export const DOWNLOAD_FILE_BY_ID_STARTED = 'DOWNLOAD_FILE_BY_ID_STARTED';
export const DOWNLOAD_FILE_BY_ID_FAILURE = 'DOWNLOAD_FILE_BY_ID_FAILURE';

// PROCESSES

export const GET_PROCESSES_STARTED = 'GET_PROCESSES_STARTED';
export const GET_PROCESSES_SUCCESS = 'GET_PROCESSES_SUCCESS';
export const GET_PROCESSES_FAILURE = 'GET_PROCESSES_FAILURE';

export const GET_DISTRICT_PROCESSES_TKO_STARTED = 'GET_DISTRICT_PROCESSES_TKO_STARTED';
export const GET_DISTRICT_PROCESSES_TKO_SUCCESS = 'GET_DISTRICT_PROCESSES_TKO_SUCCESS';
export const GET_DISTRICT_PROCESSES_TKO_FAILURE = 'GET_DISTRICT_PROCESSES_TKO_FAILURE';

export const START_DISTRICT_PROCESSES_TKO_STARTED = 'START_DISTRICT_PROCESSES_TKO_STARTED';
export const START_DISTRICT_PROCESSES_TKO_SUCCESS = 'START_DISTRICT_PROCESSES_TKO_SUCCESS';
export const START_DISTRICT_PROCESSES_TKO_FAILURE = 'START_DISTRICT_PROCESSES_TKO_FAILURE';

export const CANCEL_DISTRICT_PROCESSES_TKO_STARTED = 'CANCEL_DISTRICT_PROCESSES_TKO_STARTED';
export const CANCEL_DISTRICT_PROCESSES_TKO_SUCCESS = 'CANCEL_DISTRICT_PROCESSES_TKO_SUCCESS';
export const CANCEL_DISTRICT_PROCESSES_TKO_FAILURE = 'CANCEL_DISTRICT_PROCESSES_TKO_FAILURE';

export const DONE_DISTRICT_PROCESSES_TKO_STARTED = 'DONE_DISTRICT_PROCESSES_TKO_STARTED';
export const DONE_DISTRICT_PROCESSES_TKO_SUCCESS = 'DONE_DISTRICT_PROCESSES_TKO_SUCCESS';
export const DONE_DISTRICT_PROCESSES_TKO_FAILURE = 'DONE_DISTRICT_PROCESSES_TKO_FAILURE';

export const UPLOAD_FILES_DISTRICT_PROCESSES_TKO_STARTED = 'UPLOAD_FILES_DISTRICT_PROCESSES_TKO_STARTED';
export const UPLOAD_FILES_DISTRICT_PROCESSES_TKO_SUCCESS = 'UPLOAD_FILES_DISTRICT_PROCESSES_TKO_SUCCESS';
export const UPLOAD_FILES_DISTRICT_PROCESSES_TKO_FAILURE = 'UPLOAD_FILES_DISTRICT_PROCESSES_TKO_FAILURE';

export const GET_UPDATE_TKO_DATA_PROCESSES_TKO_STARTED = 'GET_UPDATE_TKO_DATA_PROCESSES_TKO_STARTED';
export const GET_UPDATE_TKO_DATA_PROCESSES_TKO_SUCCESS = 'GET_UPDATE_TKO_DATA_PROCESSES_TKO_SUCCESS';
export const GET_UPDATE_TKO_DATA_PROCESSES_TKO_FAILURE = 'GET_UPDATE_TKO_DATA_PROCESSES_TKO_FAILURE';

export const DOWNLOAD_DISTRICT_PROCESSES_FILE_STARTED = 'DOWNLOAD_DISTRICT_PROCESSES_FILE_STARTED';
export const DOWNLOAD_DISTRICT_PROCESSES_FILE_SUCCESS = 'DOWNLOAD_DISTRICT_PROCESSES_FILE_SUCCESS';
export const DOWNLOAD_DISTRICT_PROCESSES_FILE_FAILURE = 'DOWNLOAD_DISTRICT_PROCESSES_FILE_FAILURE';

export const CURRENT_PROCESS = {
  FETCH_STARTED: 'CURRENT_PROCESS_FETCH_STARTED',
  FETCH_FAILURE: 'CURRENT_PROCESS_FETCH_FAILURE',
  FETCH_FAILURE_WITHOUT_MESSAGE: 'CURRENT_PROCESS_FETCH_FAILURE_WITHOUT_MESSAGE',
  SET_DATA: 'CURRENT_PROCESS_SET_DATA',
  CLEAR: 'CURRENT_PROCESS_CLEAR',
  UPDATE: 'CURRENT_PROCESS_UPDATE',
  SET_PARAMS: 'CURRENT_PROCESS_SET_PARAMS',
  CLEAR_PARAMS: 'CURRENT_PROCESS_CLEAR_PARAMS'
};

// PON

export const GET_PON_SUPPLIERS_STARTED = 'GET_PON_SUPPLIERS_STARTED';
export const GET_PON_SUPPLIERS_SUCCESS = 'GET_PON_SUPPLIERS_SUCCESS';
export const GET_PON_SUPPLIERS_FAILURE = 'GET_PON_SUPPLIERS_FAILURE';

export const SEARCH_PON_SUPPLIERS_STARTED = 'SEARCH_PON_SUPPLIERS_STARTED';
export const SEARCH_PON_SUPPLIERS_SUCCESS = 'SEARCH_PON_SUPPLIERS_SUCCESS';
export const SEARCH_PON_SUPPLIERS_FAILURE = 'SEARCH_PON_SUPPLIERS_FAILURE';

export const CLEAR_PON_SUPPLIERS = 'CLEAR_PON_SUPPLIERS';

export const GET_PON_REASONS_STARTED = 'GET_PON_REASONS_STARTED';
export const GET_PON_REASONS_SUCCESS = 'GET_PON_REASONS_SUCCESS';
export const GET_PON_REASONS_FAILURE = 'GET_PON_REASONS_FAILURE';

export const CREATE_PON_STARTED = 'CREATE_PON_STARTED';
export const CREATE_PON_SUCCESS = 'CREATE_PON_SUCCESS';
export const CREATE_PON_FAILURE = 'CREATE_PON_FAILURE';

export const GET_PON_BY_ID_STARTED = 'GET_PON_BY_ID_STARTED';
export const GET_PON_BY_ID_SUCCESS = 'GET_PON_BY_ID_SUCCESS';
export const GET_PON_BY_ID_FAILURE = 'GET_PON_BY_ID_FAILURE';

export const CANCEL_PON_STARTED = 'CANCEL_PON_STARTED';
export const CANCEL_PON_SUCCESS = 'CANCEL_PON_SUCCESS';
export const CANCEL_PON_FAILURE = 'CANCEL_PON_FAILURE';

export const CLEAR_PON_REDUCER = 'CLEAR_PON_REDUCER';

export const EXPORT_PON_TKO_STARTED = 'EXPORT_PON_TKO_STARTED';
export const EXPORT_PON_TKO_SUCCESS = 'EXPORT_PON_TKO_SUCCESS';
export const EXPORT_PON_TKO_FAILURE = 'EXPORT_PON_TKO_FAILURE';

export const GET_PON_REQUESTS_DATA_STARTED = 'GET_PON_REQUESTS_DATA_STARTED';
export const GET_PON_REQUESTS_DATA_SUCCESS = 'GET_PON_REQUESTS_DATA_SUCCESS';
export const GET_PON_REQUESTS_DATA_FAILURE = 'GET_PON_REQUESTS_DATA_FAILURE';
export const SET_PON_REQUESTS_DATA_PARAMS = 'SET_PON_REQUESTS_DATA_PARAMS';
export const CLEAR_PON_REQUESTS = 'CLEAR_PON_REQUESTS';

export const GET_PON_REQUEST_TKO_STARTED = 'GET_PON_REQUEST_TKO_STARTED';
export const GET_PON_REQUEST_TKO_SUCCESS = 'GET_PON_REQUEST_TKO_SUCCESS';
export const CLEAR_PON_REQUEST_TKO_LOADING = 'CLEAR_PON_REQUEST_TKO_LOADING';
export const GET_PON_REQUEST_TKO_FAILURE = 'GET_PON_REQUEST_TKO_FAILURE';
export const CLEAR_PON_REQUEST_TKO = 'CLEAR_PON_REQUEST_TKO';
export const DOWNLOAD_PON_REQUEST_TKO_FILE_FAILURE = 'DOWNLOAD_PON_REQUEST_TKO_FILE_FAILURE';

export const GET_PON_INFORMING_LIST_STARTED = 'GET_PON_INFORMING_LIST_STARTED';
export const GET_PON_INFORMING_LIST_SUCCESS = 'GET_PON_INFORMING_LIST_SUCCESS';
export const GET_PON_INFORMING_LIST_FAILURE = 'GET_PON_INFORMING_LIST_FAILURE';
export const CLEAR_PON_INFORMING_LIST = 'CLEAR_PON_INFORMING_LIST';
export const SET_PON_INFORMING_LIST_PARAMS = 'SET_PON_INFORMING_LIST_PARAMS';
export const DOWNLOAD_PON_INFORMING_FILE_FAILURE = 'DOWNLOAD_PON_INFORMING_FILE_FAILURE';

export const GET_PON_INFORMING_DETAIL_STARTED = 'GET_PON_INFORMING_DETAIL_STARTED';
export const GET_PON_INFORMING_DETAIL_SUCCESS = 'GET_PON_INFORMING_DETAIL_SUCCESS';
export const GET_PON_INFORMING_DETAIL_FAILURE = 'GET_PON_INFORMING_DETAIL_FAILURE';
export const CLEAR_PON_INFORMING_DETAIL = 'CLEAR_PON_INFORMING_DETAIL';

export const GET_PON_REQUEST_DKO_DETAILS_STARTED = 'GET_PON_REQUEST_DKO_DETAILS_STARTED';
export const GET_PON_REQUEST_DKO_DETAILS_SUCCESS = 'GET_PON_REQUEST_DKO_DETAILS_SUCCESS';
export const GET_PON_REQUEST_DKO_DETAILS_FAILURE = 'GET_PON_REQUEST_DKO_DETAILS_FAILURE';
export const CLEAR_PON_REQUEST_DKO_DETAILS = 'CLEAR_PON_REQUEST_DKO_DETAILS';

// ADMIN

export const GET_ALL_USERS_STARTED = 'GET_ALL_USERS_STARTED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const SET_ADMIN_PARAMS = 'SET_ADMIN_PARAMS';
export const CLEAR_ADMIN_PARAMS = 'CLEAR_ADMIN_PARAMS';
export const CLEAR_ADMIN_ERROR = 'CLEAR_ADMIN_ERROR';

export const GET_ALL_ROLES_STARTED = 'GET_ALL_ROLES_STARTED';
export const GET_ALL_ROLES_SUCCESS = 'GET_ALL_ROLES_SUCCESS';
export const GET_ALL_ROLES_FAILURE = 'GET_ALL_ROLES_FAILURE';

export const GET_ALL_ORGANIZATIONS_STARTED = 'GET_ALL_ORGANIZATIONS_STARTED';
export const GET_ALL_ORGANIZATIONS_SUCCESS = 'GET_ALL_ORGANIZATIONS_SUCCESS';
export const GET_ALL_ORGANIZATIONS_FAILURE = 'GET_ALL_ORGANIZATIONS_FAILURE';

export const CREATE_USER_STARTED = 'CREATE_USER_STARTED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const GET_USER_BY_ID_STARTED = 'GET_USER_BY_ID_STARTED';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const UPDATE_USER_BY_ID_STARTED = 'UPDATE_USER_BY_ID_STARTED';
export const UPDATE_USER_BY_ID_SUCCESS = 'UPDATE_USER_BY_ID_SUCCESS';
export const UPDATE_USER_BY_ID_FAILURE = 'UPDATE_USER_BY_ID_FAILURE';

export const RESET_PASSWORD_STARTED = 'RESET_PASSWORD_STARTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const UPDATE_API_KEY_SUCCESS = 'UPDATE_API_KEY_SUCCESS';
export const UPDATE_API_KEY_FAILURE = 'UPDATE_API_KEY_FAILURE';

export const GENERATE_LOGIN_STARTED = 'GENERATE_LOGIN_STARTED';
export const GENERATE_LOGIN_SUCCESS = 'GENERATE_LOGIN_SUCCESS';
export const GENERATE_LOGIN_FAILURE = 'GENERATE_LOGIN_FAILURE';

export const CLEAR_ADMIN_TEMPLATES = 'CLEAR_ADMIN_TEMPLATES';

export const CREATE_TEMPLATES_STARTED = 'CREATE_TEMPLATES_STARTED';
export const CREATE_TEMPLATES_SUCCESS = 'CREATE_TEMPLATES_SUCCESS';
export const CREATE_TEMPLATES_FAILURE = 'CREATE_TEMPLATES_FAILURE';

export const GET_TEMPLATES_CHECKED_STARTED = 'GET_TEMPLATES_CHECKED_STARTED';
export const GET_TEMPLATES_CHECKED_FAILURE = 'GET_TEMPLATES_CHECKED_FAILURE';
export const GET_TEMPLATES_CHECKED_SUCCESS = 'GET_TEMPLATES_CHECKED_SUCCESS';

export const GET_TEMPLATES_LIST_STARTED = 'GET_TEMPLATES_LIST_STARTED';
export const GET_TEMPLATES_LIST_FAILURE = 'GET_TEMPLATES_LIST_FAILURE';
export const GET_TEMPLATES_LIST_SUCCESS = 'GET_TEMPLATES_LIST_SUCCESS';

// PASSWORDS

export const VERIFY_PASSWORD_TOKEN_SUCCESS = 'VERIFY_PASSWORD_TOKEN_SUCCESS';
export const VERIFY_PASSWORD_TOKEN_FAILURE = 'VERIFY_PASSWORD_TOKEN_FAILURE';

export const CREATE_PASSWORD_STARTED = 'CREATE_PASSWORD_STARTED';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAILURE = 'CREATE_PASSWORD_FAILURE';

export const CREATE_OTP_STARTED = 'CREATE_OTP_STARTED';
export const CREATE_OTP_SUCCESS = 'CREATE_OTP_SUCCESS';
export const CREATE_OTP_FAILURE = 'CREATE_OTP_FAILURE';

export const CLEAR_PASSWORD_STATE = 'CLEAR_PASSWORD_STATE';

// PPKO

export const GET_PPKO_LIST_STARTED = 'GET_PPKO_LIST_STARTED';
export const GET_PPKO_LIST_SUCCESS = 'GET_PPKO_LIST_SUCCESS';
export const GET_PPKO_LIST_FAILURE = 'GET_PPKO_LIST_FAILURE';

export const SET_PPKO_LIST_PARAMS = 'SET_PPKO_LIST_PARAMS';
export const CLEAR_PPKO_LIST_PARAMS = 'CLEAR_PPKO_LIST_PARAMS';

export const GET_PPKO_BY_ID_STARTED = 'GET_PPKO_BY_ID_STARTED';
export const GET_PPKO_BY_ID_SUCCESS = 'GET_PPKO_BY_ID_SUCCESS';
export const GET_PPKO_BY_ID_FAILURE = 'GET_PPKO_BY_ID_FAILURE';
export const GET_PPKO_BY_ID_CLEAR = 'GET_PPKO_BY_ID_CLEAR';

export const DOWNLOAD_PPKO_BY_ID_STARTED = 'DOWNLOAD_PPKO_BY_ID_STARTED';
export const DOWNLOAD_PPKO_BY_ID_SUCCESS = 'DOWNLOAD_PPKO_BY_ID_SUCCESS';
export const DOWNLOAD_PPKO_BY_ID_FAILURE = 'DOWNLOAD_PPKO_BY_ID_FAILURE';

export const DOWNLOAD_PPKO_EXTERNAL_FILE_BY_ID_STARTED = 'DOWNLOAD_PPKO_EXTERNAL_FIL_BY_ID_STARTED';
export const DOWNLOAD_PPKO_EXTERNAL_FILE_BY_ID_SUCCESS = 'DOWNLOAD_PPKO_EXTERNAL_FIL_BY_ID_SUCCESS';
export const DOWNLOAD_PPKO_EXTERNAL_FILE_BY_ID_FAILURE = 'DOWNLOAD_PPKO_EXTERNAL_FIL_BY_ID_FAILURE';

export const UPLOAD_PPKO_DOCUMENT_CLEAR = 'UPLOAD_PPKO_DOCUMENT_CLEAR';

export const UPLOAD_PPKO_DOCUMENT_STARTED = 'UPLOAD_PPKO_DOCUMENT_STARTED';
export const UPLOAD_PPKO_DOCUMENT_SUCCESS = 'UPLOAD_PPKO_DOCUMENT_SUCCESS';
export const UPLOAD_PPKO_DOCUMENT_FAILURE = 'UPLOAD_PPKO_DOCUMENT_FAILURE';

export const SAVE_PPKO_DOCUMENT_STARTED = 'SAVE_PPKO_DOCUMENT_STARTED';
export const SAVE_PPKO_DOCUMENT_SUCCESS = 'SAVE_PPKO_DOCUMENT_SUCCESS';
export const SAVE_PPKO_DOCUMENT_FAILURE = 'SAVE_PPKO_DOCUMENT_FAILURE';

export const UPLOAD_PPKO_DOCUMENT_FILE_STARTED = 'UPLOAD_PPKO_DOCUMENT_FILE_STARTED';
export const UPLOAD_PPKO_DOCUMENT_FILE_SUCCESS = 'UPLOAD_PPKO_DOCUMENT_FILE_SUCCESS';
export const UPLOAD_PPKO_DOCUMENT_FILE_FAILURE = 'UPLOAD_PPKO_DOCUMENT_FILE_FAILURE';

export const DOWNLOAD_PPKO_DOCUMENT_FILE_STARTED = 'DOWNLOAD_PPKO_DOCUMENT_FILE_STARTED';
export const DOWNLOAD_PPKO_DOCUMENT_FILE_SUCCESS = 'DOWNLOAD_PPKO_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_PPKO_DOCUMENT_FILE_FAILURE = 'DOWNLOAD_PPKO_DOCUMENT_FILE_FAILURE';

export const GET_PUBLICATION_EMAILS_STARTED = 'GET_PUBLICATION_EMAILS_STARTED';
export const GET_PUBLICATION_EMAILS_SUCCESS = 'GET_PUBLICATION_EMAILS_SUCCESS';
export const GET_PUBLICATION_EMAILS_FAILURE = 'GET_PUBLICATION_EMAILS_FAILURE';

export const UPDATE_PUBLICATION_EMAILS_STARTED = 'UPDATE_PUBLICATION_EMAILS_STARTED';
export const UPDATE_PUBLICATION_EMAILS_SUCCESS = 'UPDATE_PUBLICATION_EMAILS_SUCCESS';
export const UPDATE_PUBLICATION_EMAILS_FAILURE = 'UPDATE_PUBLICATION_EMAILS_FAILURE';

export const PPKO_PUBLICATION_STARTED = 'PPKO_PUBLICATION_STARTED';
export const PPKO_PUBLICATION_SUCCESS = 'PPKO_PUBLICATION_SUCCESS';
export const PPKO_PUBLICATION_FAILURE = 'PPKO_PUBLICATION_FAILURE';

export const CLEAR_PPKO_CHECK = 'CLEAR_PPKO_CHECK';

export const GET_PPKO_CHECK_BY_ID_STARTED = 'GET_PPKO_CHECK_BY_ID_STARTED';
export const GET_PPKO_CHECK_BY_ID_SUCCESS = 'GET_PPKO_CHECK_BY_ID_SUCCESS';
export const GET_PPKO_CHECK_BY_ID_FAILURE = 'GET_PPKO_CHECK_BY_ID_FAILURE';

export const SAVE_PPKO_CHECK_STARTED = 'SAVE_PPKO_CHECK_STARTED';
export const SAVE_PPKO_CHECK_SUCCESS = 'SAVE_PPKO_CHECK_SUCCESS';
export const SAVE_PPKO_CHECK_FAILURE = 'SAVE_PPKO_CHECK_FAILURE';

export const GET_NAMES_CHECK_DOCK_STARTED = 'GET_NAMES_CHECK_DOCK_STARTED';
export const GET_NAMES_CHECK_DOCK_SUCCESS = 'GET_NAMES_CHECK_DOCK_SUCCESS';

// Directories

export const SET_DIRECTORY_LIST_PARAMS = 'SET_DIRECTORY_LIST_PARAMS';
export const CLEAR_DIRECTORY_LIST_PARAMS = 'CLEAR_DIRECTORY_LIST_PARAMS';

export const GET_DIRECTORY_LIST_STARTED = 'GET_DIRECTORY_LIST_STARTED';
export const GET_DIRECTORY_LIST_SUCCESS = 'GET_DIRECTORY_LIST_SUCCESS';
export const GET_DIRECTORY_LIST_FAILURE = 'GET_DIRECTORY_LIST_FAILURE';

export const GET_DIRECTORY_BY_ID_STARTED = 'GET_DIRECTORY_BY_ID_STARTED';
export const GET_DIRECTORY_BY_ID_SUCCESS = 'GET_DIRECTORY_BY_ID_SUCCESS';
export const GET_DIRECTORY_BY_ID_FAILURE = 'GET_DIRECTORY_BY_ID_FAILURE';

export const ADD_ITEM_TO_DIRECTORY_STARTED = 'ADD_ITEM_TO_DIRECTORY_STARTED';
export const ADD_ITEM_TO_DIRECTORY_SUCCESS = 'ADD_ITEM_TO_DIRECTORY_SUCCESS';
export const ADD_ITEM_TO_DIRECTORY_FAILURE = 'ADD_ITEM_TO_DIRECTORY_FAILURE';

export const SET_ARCHIVE_DIRECTORY_DIALOG = 'SET_ARCHIVE_DIRECTORY_DIALOG';
export const REMOVE_ARCHIVE_DIRECTORY_DIALOG = 'REMOVE_ARCHIVE_DIRECTORY_DIALOG';

export const ARCHIVE_DIRECTORY_FAILURE = 'ARCHIVE_DIRECTORY_FAILURE';

export const DOWNLOAD_DIRECTORY_STARTED = 'DOWNLOAD_DIRECTORY_STARTED';
export const DOWNLOAD_DIRECTORY_SUCCESS = 'DOWNLOAD_DIRECTORY_SUCCESS';
export const DOWNLOAD_DIRECTORY_FAILURE = 'DOWNLOAD_DIRECTORY_FAILURE';

export const UPLOAD_SUPPLIERS_DIRECTORY_STARTED = 'UPLOAD_SUPPLIERS_DIRECTORY_STARTED';
export const UPLOAD_SUPPLIERS_DIRECTORY_SUCCESS = 'UPLOAD_SUPPLIERS_DIRECTORY_SUCCESS';
export const UPLOAD_SUPPLIERS_DIRECTORY_FAILURE = 'UPLOAD_SUPPLIERS_DIRECTORY_FAILURE';
export const CLOSE_SUPPLIERS_DIRECTORY_DIALOGS = 'CLOSE_SUPPLIERS_DIRECTORY_DIALOGS';

export const DOWNLOAD_SUPPLIERS_UPDATE_RESULTS_STARTED = 'DOWNLOAD_SUPPLIERS_UPDATE_RESULTS_STARTED';
export const DOWNLOAD_SUPPLIERS_UPDATE_RESULTS_FAILURE = 'DOWNLOAD_SUPPLIERS_UPDATE_RESULTS_FAILURE';

// TimeSeries

export const GET_TS_LIST_STARTED = 'GET_TS_LIST_STARTED';
export const GET_TS_LIST_SUCCESS = 'GET_TS_LIST_SUCCESS';
export const GET_TS_LIST_FAILURE = 'GET_TS_LIST_FAILURE';

export const SET_TS_LIST_PARAMS = 'SET_TS_LIST_PARAMS';

export const GET_TS_FILE_BY_ID_STARTED = 'GET_TS_FILE_BY_ID_STARTED';
export const GET_TS_FILE_BY_ID_SUCCESS = 'GET_TS_FILE_BY_ID_SUCCESS';
export const GET_TS_FILE_BY_ID_FAILURE = 'GET_TS_FILE_BY_ID_FAILURE';

export const SET_TS_DIALOG_OPEN = 'SET_TS_DIALOG_OPEN';

export const UPLOAD_TS_FILE_STARTED = 'UPLOAD_TS_FILE_STARTED';
export const UPLOAD_TS_FILE_SUCCESS = 'UPLOAD_TS_FILE_SUCCESS';
export const UPLOAD_TS_FILE_FAILURE = 'UPLOAD_TS_FILE_FAILURE';
export const UPLOAD_TS_FILE_CLEAR = 'UPLOAD_TS_FILE_CLEAR';

// INSTRUCTIONS

export const DOWNLOAD_INSTRUCTION_STARTED = 'DOWNLOAD_INSTRUCTION_STARTED';
export const DOWNLOAD_INSTRUCTION_FAILURE = 'DOWNLOAD_INSTRUCTION_FAILURE';

// REPORTS
export const GET_REPORTS_LIST_STARTED = 'GET_REPORTS_LIST_STARTED';
export const GET_REPORTS_LIST_SUCCESS = 'GET_REPORTS_LIST_SUCCESS';
export const GET_REPORTS_LIST_FAILURE = 'GET_REPORTS_LIST_FAILURE';

export const DOWNLOAD_REPORT_STARTED = 'DOWNLOAD_REPORT_STARTED';
export const DOWNLOAD_REPORT_SUCCESS = 'DOWNLOAD_REPORT_SUCCESS';
export const DOWNLOAD_REPORT_FAILURE = 'DOWNLOAD_REPORT_FAILURE';

// END OF SUPPLY

export const EOS_GET_INIT_LIST_STARTED = 'EOS_GET_INIT_LIST_STARTED';
export const EOS_GET_INIT_LIST_SUCCESS = 'EOS_GET_INIT_LIST_SUCCESS';
export const EOS_GET_INIT_LIST_FAILURE = 'EOS_GET_INIT_LIST_FAILURE';
export const EOS_SET_INIT_LIST_PARAMS = 'EOS_SET_INIT_LIST_PARAMS';

export const EOS_CREATE_STARTED = 'EOS_CREATE_STARTED';
export const EOS_CREATE_SUCCESS = 'EOS_CREATE_SUCCESS';
export const EOS_CREATE_FAILURE = 'EOS_CREATE_FAILURE';

export const EOS_GET_DATA_STARTED = 'EOS_GET_DATA_STARTED';
export const EOS_GET_DATA_SUCCESS = 'EOS_GET_DATA_SUCCESS';
export const EOS_GET_DATA_FAILURE = 'EOS_GET_DATA_FAILURE';

// MMS

export const MMS_GET_INFO_STARTED = 'MMS_GET_INFO_STARTED';
export const MMS_GET_INFO_SUCCESS = 'MMS_GET_INFO_SUCCESS';
export const MMS_GET_INFO_FAILURE = 'MMS_GET_INFO_FAILURE';
export const MMS_UPLOAD_FILE_STARTED = 'MMS_GET_INFO_STARTED';
export const MMS_UPLOAD_FILE_FAILURE = 'MMS_GET_INFO_FAILURE';
export const MMS_SET_PARAMS = 'MMS_SET_PARAMS';
export const MMS_SET_FAILURE_MODAL = 'MMS_SET_FAILURE_MODAL';
export const MMS_GET_SUCCESS_MODAL_STARTED = 'MMS_GET_SUCCESS_MODAL_STARTED';
export const MMS_GET_SUCCESS_MODAL_SUCCESS = 'MMS_GET_SUCCESS_MODAL_SUCCESS';
export const MMS_GET_SUCCESS_MODAL_FAILURE = 'MMS_GET_SUCCESS_MODAL_FAILURE';
export const MMS_CLOSE_SUCCESS_MODAL = 'MMS_CLOSE_SUCCESS_MODAL';

// SUPPLIERS

export const SUPPLIERS = {
  CLEAR_DATA: 'CLEAR_SUPPLIERS_DATA',
  SET_PARAMS: 'SUPPLIERS_SET_PARAMS',
  GET_LIST: {
    STARTED: 'GET_SUPPLIERS_LIST_STARTED',
    SUCCESS: 'GET_SUPPLIERS_LIST_SUCCESS',
    ACTIVATION_LIST_SUCCESS: 'GET_SUPPLIERS_LIST_ACTIVATION_LIST_SUCCESS',
    FAILURE: 'GET_SUPPLIERS_LIST_FAILURE'
  },
  GET_BY_UID: {
    STARTED: 'GET_SUPPLIER_BY_UID_STARTED',
    SUCCESS: 'GET_SUPPLIER_BY_UID_SUCCESS',
    FAILURE: 'GET_SUPPLIER_BY_UID_FAILURE'
  },
  SET_SELECTED: 'SUPPLIERS_SET_SELECTED',
  UPDATE_STATUS: {
    STARTED: 'SUPPLIERS_UPDATE_STATUS_STARTED',
    SUCCESS: 'SUPPLIERS_UPDATE_STATUS_SUCCESS',
    FAILURE: 'SUPPLIERS_UPDATE_STATUS_FAILURE'
  },
  DOWNLOAD: {
    STARTED: 'SUPPLIERS_DOWNLOAD_STARTED',
    SUCCESS: 'SUPPLIERS_DOWNLOAD_SUCCESS',
    FAILURE: 'SUPPLIERS_DOWNLOAD_FAILURE'
  }
};

// GTS

export const GTS = {
  GET_LIST_STARTED: 'GTS_GET_LIST_STARTED',
  GET_LIST_SUCCESS: 'GTS_GET_LIST_SUCCESS',
  GET_UPLOADED_FILES_SUCCESS: 'GTS_GET_UPLOADED_FILES_SUCCESS',
  GET_RESULT_LIST_SUCCESS: 'GTS_GET_RESULT_LIST_SUCCESS',
  GET_LIST_FAILURE: 'GTS_GET_LIST_FAILURE',
  SET_LIST_PARAMS: 'GTS_SET_LIST_PARAMS',
  CLEAR: 'GTS_CLEAR',
  GET_DKO_DATA_STARTED: 'GTS_GET_DKO_DATA_STARTED',
  GET_DKO_DATA_SUCCESS: 'GTS_GET_DKO_DATA_SUCCESS',
  GET_DKO_DATA_FAILURE: 'GTS_GET_DKO_DATA_FAILURE',
  CLEAR_DKO_DATA: 'GTS_CLEAR_DKO_DATA',
  GET_REPORTS_STARTED: 'GET_REPORTS_STARTED',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',
  GET_REPORTS_FAILURE: 'GET_REPORTS_FAILURE',
  DOWNLOAD_TKO_REPORT_STARTED: 'GTS_DOWNLOAD_TKO_REPORT_STARTED',
  DOWNLOAD_TKO_REPORT_SUCCESS: 'GTS_DOWNLOAD_TKO_REPORT_SUCCESS',
  DOWNLOAD_TKO_REPORT_FAILURE: 'GTS_DOWNLOAD_TKO_REPORT_FAILURE',
  DOWNLOAD_REPORT_STARTED: 'GTS_DOWNLOAD_REPORT_STARTED',
  DOWNLOAD_REPORT_SUCCESS: 'GTS_DOWNLOAD_REPORT_SUCCESS',
  DOWNLOAD_REPORT_FAILURE: 'GTS_DOWNLOAD_REPORT_FAILURE',
  GTS_REVOKE_REPORT_STARTED: 'GTS_REVOKE_REPORT_STARTED',
  GTS_REVOKE_REPORT_SUCCESS: 'GTS_REVOKE_REPORT_SUCCESS',
  GTS_REVOKE_REPORT_FAILURE: 'GTS_REVOKE_REPORT_FAILURE',
  SET_REPORT_FILTERS: 'SET_GTS_REPORT_FILTERS',
  ERROR: 'GTS_FAILURE',
  UPDATE_REPORT_BY_EIC_STARTED: 'GTS_UPDATE_REPORT_BY_EIC_STARTED',
  UPDATE_REPORT_BY_EIC_SUCCESS: 'GTS_UPDATE_REPORT_BY_EIC_SUCCESS',
  CREATE_REPORT_BY_EIC_SUCCESS: 'GTS_CREATE_REPORT_BY_EIC_SUCCESS',
  CREATE_EMPTY_REPORT_BY_EIC_SUCCESS: 'CREATE_EMPTY_REPORT_BY_EIC_SUCCESS',
  UPDATE_REPORT_BY_RELEASE: 'GTS_UPDATE_REPORT_BY_CODE',
  CREATE_REPORT_BY_RELEASE_STARTED: 'GTS_CREATE_REPORT_BY_RELEASE_STARTED',
  CREATE_REPORT_BY_RELEASE_SUCCESS: 'GTS_CREATE_REPORT_BY_RELEASE_SUCCESS',
  CREATE_REPORT_BY_RELEASE_FAILURE: 'GTS_CREATE_REPORT_BY_RELEASE_FAILURE',
  CLEAR_UP: 'GTS_CLEAR_UP',
  GET_EIC_Y_LIST_SUCCESS: 'GET_EIC_Y_LIST_SUCCESS',
  UPDATE_REPORT_BY_ZV_STARTED: 'GTS_UPDATE_REPORT_BY_ZV_STARTED',
  UPDATE_REPORT_BY_ZV_SUCCESS: 'GTS_UPDATE_REPORT_BY_ZV_SUCCESS',
  CREATE_REPORT_BY_ZV_SUCCESS: 'GTS_CREATE_REPORT_BY_ZV_SUCCESS',
  GENERAL_SETTINGS_REPORT_STARTED: 'GTS_GENERAL_SETTINGS_REPORT_STARTED',
  GENERAL_SETTINGS_REPORT_SUCCESS: 'GTS_GENERAL_SETTINGS_REPORT_SUCCESS',
  GENERAL_SETTINGS_REPORT_FAILURE: 'GTS_GENERAL_SETTINGS_REPORT_FAILURE',
  UPDATE_REPORT_BY_RELEASE_STARTED: 'UPDATE_REPORT_BY_RELEASE_STARTED',
  UPDATE_REPORT_BY_RELEASE_SUCCESS: 'UPDATE_REPORT_BY_RELEASE_SUCCESS',
  SET_UID_FOR_DIFFERENT_REPORTS: 'GTS_SET_UID_FOR_DIFFERENT_REPORTS',
  SET_QUALITY_TYPE_LIST: 'GTS_SET_QUALITY_TYPE_LIST',
  DELETE_ALL_TKOS: 'GTS_DELETE_ALL_TKOS',
  UPDATE_REPORT_BY_COMPONENTS_ZV_STARTED: 'GTS_UPDATE_REPORT_BY_COMPONENTS_ZV_STARTED',
  UPDATE_REPORT_BY_COMPONENTS_ZV_SUCCESS: 'GTS_UPDATE_REPORT_BY_COMPONENTS_ZV_SUCCESS',
  CREATE_REPORT_BY_COMPONENTS_ZV_SUCCESS: 'GTS_CREATE_REPORT_BY_COMPONENTS_ZV_SUCCESS',
  ORIGINAL_SETTINGS_DATA: 'INIT_FILTER_DATA',
  UPDATE_REPORT_BY_VERSION_STARTED: 'GTS_UPDATE_REPORT_BY_VERSION_STARTED',
  UPDATE_REPORT_BY_VERSION_SUCCESS: 'GTS_UPDATE_REPORT_BY_VERSION_SUCCESS',
  CREATE_REPORT_BY_VERSION_SUCCESS: 'GTS_CREATE_REPORT_BY_VERSION_SUCCESS',
  DELETE_ALL_TKOS_BY_VERSION: 'GTS_DELETE_ALL_TKOS_BY_VERSION',
};

// ZV

export const ZV = {
  GET_LIST_STARTED: 'ZV_GET_LIST_STARTED',
  GET_LIST_SUCCESS: 'ZV_GET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'ZV_GET_LIST_FAILURE',
  CLEAR: 'ZV_CLEAR'
};
