import i18n from "../../../i18n/i18n";

const TEXT = {
  uk: {
    pageTitle: i18n.t('NOTIFICATIONS.NOTIFICATIONS'),
    buttonResetAll: i18n.t('NOTIFICATIONS.DEFAULT_SETTINGS')
  }
};

const PROCESSES = {
  uk: [
    i18n.t('SUBPROCESSES.CONNECT_TKO'),
    i18n.t('SUBPROCESSES.DISCONNECT_TKO'),
    i18n.t('PROCESSES.CONNECTING_DISCONNECTING'),
    i18n.t('SUBPROCESSES.EXPORT_TKO'),
    i18n.t('SUBPROCESSES.PON_PUP'),
    i18n.t('SUBPROCESSES.REQUEST_DATA_IN_ATKO'),
    i18n.t('SUBPROCESSES.REQUEST_HISTORICAL_DKO'),
    i18n.t('SUBPROCESSES.REQUEST_ACTUAL_DKO'),
    i18n.t('SUBPROCESSES.REQUESTS_TKO_DATA'),
    i18n.t('SUBPROCESSES.INFORMING_PON_PUP'),
    i18n.t('SUBPROCESSES.RESPONSE_ACTUAL_DKO'),
    i18n.t('SUBPROCESSES.UPDATE_TKO_DATA'),
    i18n.t('SUBPROCESSES.INITIALIZATION_BY_SUPPLIER'),
    i18n.t('SUBPROCESSES.INITIALIZATION_BY_SUPPLIER_FOR_AKO'),
    i18n.t('SUBPROCESSES.PON_PUP_AP'),
    i18n.t('SUBPROCESSES.INITIALIZATION_PON_AUTO'),
    i18n.t('SUBPROCESSES.PROLONGATION_CONTRACT'),
    i18n.t('SUBPROCESSES.EXTENSION_TERM_OF_SUPPLY_CONTRACT'),
    i18n.t('SUBPROCESSES.CHANGE_SUPPLIET_TO_SUPPLIER'),
    i18n.t('SUBPROCESSES.CHANGE_SUPPLIET'),
    i18n.t('SUBPROCESSES.PON'),
    i18n.t('SUBPROCESSES.RECEIVING_DKO_ACTUAL'),
    i18n.t('SUBPROCESSES.RECEIVING_DKO_HISTORICAL'),
    i18n.t('PAGES.DISPUTE'),
    i18n.t('SUBPROCESSES.DISPUTE_UPDATE_TKO_DATA'),
    i18n.t('SUBPROCESSES.DISPUTE_REQUEST_DATA_IN_ATKO'),
    i18n.t('SUBPROCESSES.TERMINATION_SUPPLY'),
    i18n.t('SUBPROCESSES.RESUMPTION_SUPPLY'),
    i18n.t('GROUPS.END_SUPPLY'),
    i18n.t('PAGES.APPLICATION_FOR_CHANGE_OF_STATUS'),
    i18n.t('SUBPROCESSES.GRANTING_AUTHORITY'),
    i18n.t('SUBPROCESSES.PREDICTABLE_CONSUMPTION_ODKO'),
    i18n.t('SUBPROCESSES.INFORMING_ATKO_FOR_CHANGE_SUPPLIER'),
    i18n.t('SUBPROCESSES.INFORMING_CURRENT_SUPPLIER'),
    i18n.t('SUBPROCESSES.INFORMING_AKO_FOR_CHANGE_SUPPLIER'),
    i18n.t('SUBPROCESSES.CANCEL_PPKO_REGISTRATION'),
    i18n.t('SUBPROCESSES.REQUEST_CANCEL_PPKO_REGISTRATION'),
    i18n.t('SUBPROCESSES.CANCEL_PPKO_REGISTRATION_ON_EXPIRE'),
    i18n.t('GROUPS.CREATE_TKO'),
    i18n.t('SUBPROCESSES.CHANGE_PPKO_TO_OS'),
    i18n.t('SUBPROCESSES.REQUEST_CHANGE_PPKO'),
    i18n.t('SUBPROCESSES.REQUEST_CHANGE_PPKO_APPROVAL'),
  ]
};

const getText = () => TEXT['uk'] || [];

const getProcesses = ({ page, size }) => {
  let list = PROCESSES['uk']?.map((title, uid) => ({
    uid,
    title,
    toggle1: false,
    toggle2: false,
    toggle3: false
  }));
  if (!list) list = [];
  return size === -1 ? list : list.filter((v, i) => i >= (page - 1) * size && i < page * size);
};

export { getProcesses, getText, PROCESSES, TEXT };
